import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import Navbar from "./components/Navbar";
import Providers from "@/services/Providers";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<Providers>
						<SignedIn>
							<Navbar />
							{children}
						</SignedIn>
						<SignedOut>
							<SignIn />
						</SignedOut>
					</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
}
